# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "semiannually"

  - package-ecosystem: "julia"
    directories: ["/",  "/docs", "/notebooks", "/test"]
    schedule:
      interval: "quarterly"
    groups:
      all-julia-packages:
        patterns:
          - "*"
