[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GravitationalPotentials = "c5ecfa00-e6a4-4f27-837b-868bffbab2ae"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[sources.GravitationalPotentials]
path = ".."

[compat]
CairoMakie = "0.15.8"
Pluto = "0.20.21"
PlutoUI = "0.7.77"
WGLMakie = "0.13.8"
